name: OpenContainers Python Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches_ignore: []

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup black linter
        run: conda create --quiet --name black black

      - name: Lint python code
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate black
          black --check opencontainers

  testing:
    runs-on: ubuntu-latest
    needs: formatting
    steps:
      - uses: actions/checkout@v1
      
      - name: Setup Snakemake environment
        run: conda env create --quiet --name ocipython

      - name: Run tests
        env:
          CI: true
        run: |
          # enable coverage recording for subprocesses
                echo -e "try:\n    import coverage\n    coverage.process_startup()\nexcept:\n    pass" > sitecustomize.py
          export COVERAGE_PROCESS_START=.coveragerc

          # activate conda env
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate snakemake
          
          # run tests
          coverage run -m pytest tests/test*.py -v -x

          # collect coverage report
          #coverage combine
          #coverage xml

          #- name: Upload coverage report
          #uses: codecov/codecov-action@v1.0.3
          #with:
          #token: ${{secrets.CODECOV_TOKEN}}

      - name: Build container image
        run: docker build .
