name: OpenContainers Python Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches_ignore: []

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup black linter
        run: conda create --quiet --name black black

      - name: Lint python code
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate black
          black --check opencontainers

  testing:
    runs-on: ubuntu-latest
    needs: formatting
    steps:
      - uses: actions/checkout@v1
      
      - name: Setup OpenContainers Python environment
        run: |
            conda env create --quiet --name ocipython
            conda install pytest

      - name: Run tests
        env:
          CI: true
        run: |

          # activate conda env
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate ocipython
          
          # run tests
          pytest tests/test*.py -v -x
